#!/bin/sh

NAME='invoicely'
DJANGODIR=/webapps/invoicely/environment_3_8_2/invoicely
SOCKFILE=/webapps/invoicely/environment_3_8_2/run/gunicorn.sock
USER=invoicelyuser
GROUP=webapps
NUM_WORKERS=3
DJANGO_SETTINGS_MODULE=invoicely.settingsprod
DJANGO_WSGI_MODULE=invoicely.wsgi
TIMEOUT=120

cd $DJANGODIR
source ../bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

exec ../bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
--name $NAME \
--workers $NUM_WORKERS \
--timeout $TIMEOUT \
--user=$USER --group=$GROUP \
--bind=unix:$SOCKFILE \
--log-level=debug \
--log-file=-
